name: CI
on:
    pull_request:
        branches: [master]
    push:
        branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@master
         with:
            node-version: 14
       - run: npm ci
       - run: npm run build
